baseURL = "https://allanrey.es/"
languageCode = "en-us"
title = "Allan Reyes — Designer and Enthusiast"
enableGitInfo = true

[params]
AuthorName = "Allan Reyes"
GitHubUser = "ulampinoy"
GitHubRepo = "https://github.com/ulampinoy/allanreyes/"